language: python
python: 
- 2.6
- 2.7
- pypy
install: 
- pip install tox
- pip install .
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
before_install: 
- git submodule update --init --recursive
- sudo apt-get install libsnappy-dev
- ./build_integration.sh
deploy: 
  on: 
    all_branches: true
    tags: true
  provider: pypi
  user: mumrah
  password: 
    secure: XMpVNYK2hnf2zA71iFZFvxmsFBnQWNzHx9MSDby1KjFIFh4gMmp4nShGmHtFDX24+A5IY3bdSrWSVvlOqvnkdAxPkSqG6au1ypT7TMBvI8kWmcpnQFACrULD+AHJDVuSeaAK3oHmsQwYE5EMz6zxYxmtMAIGFmhZXg+8SNjTpg0=
  server: https://testpypi.python.org/pypi
script: 
- tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.0 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.1 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
