python: 
- 2.6
- 2.7
- pypy
script: 
- tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.0 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.1 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
install: 
- pip install tox
- pip install .
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
before_install: 
- git submodule update --init --recursive
- sudo apt-get install libsnappy-dev
- ./build_integration.sh
deploy: 
  on: 
    tags: true
    all_branches: true
  server: https://testpypi.python.org/pypi
  password: 
    secure: fk4xTxCkKkJQelZ1OxeWNZ2L04UPT0EoEPfm1dV8SLnG6OJEiMNFZXOlcM9BGqV+yzCFo0/+h/pdVvpw38wYa7xo7yJ1AxcMkRECSwGqSUTDtN14+dQ3wVPRY4O/LGRfiQe9oD8pomF4x8fIl8+cdnyHsEoUD/zKOX0xz+YaSSc=
  user: mumrah
  provider: pypi
language: python
