install: 
- pip install tox
- pip install .
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script: 
- tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.0 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.1 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
language: python
before_install: 
- git submodule update --init --recursive
- sudo apt-get install libsnappy-dev
- ./build_integration.sh
deploy: 
  user: mumrah
  password: 
    secure: Q8I7eCXohFcfxi7Qdgr7Nx0MBKlFx8ZjOitZA+AFv0juu3nOviIX8P2kx+VdbJwfnHDEhCipG7rwx+M8lkARj8ZJ6nMqP7BjOaksFZyq+LNn0wo0g7YcDBPt5EYp2MlYc2BxhQOvU9N/p26PrvD1bgbLBXa/lF0Ram5OUcjK/yU= 
  server: https://testpypi.python.org/pypi
  provider: pypi
  on: 
    tags: true
    all_branches: true
python: 
- 2.6
- 2.7
- pypy
