install: 
- pip install tox
- pip install .
- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
language: python
python: 
- 2.6
- 2.7
- pypy
before_install: 
- git submodule update --init --recursive
- sudo apt-get install libsnappy-dev
- ./build_integration.sh
deploy: 
  on: 
    tags: true
    all_branches: true
  server: https://testpypi.python.org/pypi
  password: 
    secure: bpyMiaz/PX10iqONMJgpZqiOwU53GN43n3zgosVhkZSVbWRP+6NsQ/xQTZE2kbUZUBMYu7QQm/3LtZVJlTrHWq29uNyJ5dBWwX92hd/MWm29RS6o63uVWk++woRuoN2FooTQ1nREnnPJmj7/T3ERUb1SkZoqBUx7sLfe2Br5ebk=
  user: mumrah
  provider: pypi
script: 
- tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.0 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
- KAFKA_VERSION=0.8.1 tox -e `./travis_selector.sh $TRAVIS_PYTHON_VERSION`
